name: Patch Repo B with Patches from Repo A

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  apply-patches:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out Repo A 
      - name: Checkout patcher_job1
        uses: actions/checkout@v3
        with:
          repository: PrachiJainTricon/patcher_job1 # Replace with the owner and name of Repo A
          path: patcher_job1

      # Step 2: Check out Repo B (the repository to apply patches to)
      - name: Checkout patcher_job2
        uses: actions/checkout@v3
        with:
          repository: PrachiJainTricon/patcher_job2 # Replace with the owner and name of Repo B
          path: patcher_job2

      # Step 3: Apply patches from Repo A to Repo B
      - name: Apply Patches
        run: |
          cp -r patcher_job1/* patcher_job2/ # Adjust this command based on what you want to copy

 # Step 4: Commit and Push Changes using PAT
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use your secret here
        run: |
          cd repo_b
          git config --global user.name "Your Name" # Replace with your name
          git config --global user.email "your_email@example.com" # Replace with your email
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Sync changes from Repo A"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/PrachiJainTricon/patcher_job2.git main # Replace 'main' with your branch name if needed
          else
            echo "No changes to commit."
          fi